/** Incrementar quando o tour ganhar passos ou mudar de forma relevante. */
export const ONBOARDING_VERSION = 2;

export const ONBOARDING_STEPS = [
  {
    id: "welcome",
    title: "Bem-vindo ao MyBoard",
    body: "Tour atualizado: Central, Agenda, Demandas, Board, financeiro, configurações e atalhos. Em poucos passos você conhece o workspace completo.",
    placement: "center",
  },
  {
    id: "dashboard-tabs",
    target: '[data-tour="dashboard-tabs"]',
    title: "Abas do workspace",
    body: "Central, Agenda, Demandas, Board, Projetos, Clientes e Lucro — cada aba concentra uma parte da operação. Vamos passar por elas.",
    placement: "bottom",
    prepare: { tab: "central", clearSelection: true, leftOpen: true, rightOpen: true },
  },
  {
    id: "sidebar-left",
    target: '[data-tour="sidebar-left"]',
    title: "Menu lateral esquerdo",
    body: "Projetos recentes, prioridades e pastas. É o mapa rápido da sua operação.",
    placement: "right",
    prepare: { tab: "central", clearSelection: true, leftOpen: true, rightOpen: true },
  },
  {
    id: "sidebar-recent",
    target: '[data-tour="sidebar-recent"]',
    title: "Recentes",
    body: "Últimos projetos abertos com avatar do cliente — ideal para retomar de onde parou.",
    placement: "right",
    prepare: { tab: "central", clearSelection: true, leftOpen: true },
  },
  {
    id: "sidebar-projects",
    target: '[data-tour="sidebar-projects"]',
    title: "Pastas e projetos",
    body: "Organize entregas em pastas, arraste projetos entre elas e crie novas pastas quando precisar.",
    placement: "right",
    prepare: { tab: "central", clearSelection: true, leftOpen: true },
  },
  {
    id: "central-hero",
    target: '[data-tour="central-hero"]',
    title: "Visão da Central",
    body: "Resumo de progresso, projetos abertos e total a receber — o que importa para o dia.",
    tooltipDock: "bottom",
    prepare: { tab: "central", clearSelection: true, scrollBlock: "start" },
  },
  {
    id: "central-timeline",
    target: '[data-tour="central-timeline"]',
    title: "Timeline semanal",
    body: "Projetos em andamento por dia da semana. Prazos vencidos aparecem em destaque.",
    tooltipAnchor: '[data-tour="central-recent"]',
    tooltipDock: "in-column",
    prepare: { tab: "central", clearSelection: true, scrollBlock: "center" },
  },
  {
    id: "central-recent",
    target: '[data-tour="central-recent"]',
    title: "Arquivos recentes",
    body: "Últimos arquivos do workspace. Use a zona de upload para anexar documentos aos projetos.",
    tooltipDock: "side-left",
    prepare: { tab: "central", clearSelection: true, scrollBlock: "center" },
  },
  {
    id: "tab-agenda",
    target: '[data-tour="tab-agenda"]',
    title: "Agenda",
    body: "Reuniões, kickoffs e compromissos. Atalho: ⇧⌘A (Mac) ou Shift+Ctrl+A (Windows).",
    placement: "bottom",
    prepare: { tab: "central", clearSelection: true },
  },
  {
    id: "agenda-view",
    target: '[data-tour="agenda-view"]',
    title: "Calendário e eventos",
    body: "Visualize por semana ou mês, crie eventos, filtre por cliente ou projeto e arraste para reagendar.",
    placement: "bottom",
    tooltipDock: "bottom",
    prepare: { tab: "agenda", clearSelection: true, scrollBlock: "start" },
  },
  {
    id: "tab-demandas",
    target: '[data-tour="tab-demandas"]',
    title: "Demandas",
    body: "Kanban de tarefas do workspace. Atalho: ⌘2.",
    placement: "bottom",
    prepare: { tab: "agenda", clearSelection: true },
  },
  {
    id: "demandas-view",
    target: '[data-tour="demandas-view"]',
    title: "Kanban de demandas",
    body: "Arraste cartões entre colunas, filtre por projeto e abra detalhes com um clique. Use Nova Demanda na barra superior.",
    placement: "bottom",
    tooltipDock: "bottom",
    prepare: { tab: "demandas", clearSelection: true, scrollBlock: "start" },
  },
  {
    id: "tab-board",
    target: '[data-tour="tab-board"]',
    title: "Board",
    body: "Quadros visuais com Excalidraw para fluxos e ideias. Atalho: ⌘3.",
    placement: "bottom",
    prepare: { tab: "demandas", clearSelection: true },
  },
  {
    id: "board-view",
    target: '[data-tour="board-view"]',
    title: "Boards visuais",
    body: "Crie boards por projeto ou cliente, desenhe livremente e abra em tela cheia quando precisar focar.",
    placement: "bottom",
    tooltipDock: "bottom",
    prepare: { tab: "board", clearSelection: true, scrollBlock: "start" },
  },
  {
    id: "tab-projetos",
    target: '[data-tour="tab-projetos"]',
    title: "Projetos",
    body: "Lista completa com prazo, pasta, valor recebido/orçamento e status. Atalho: ⌘4.",
    placement: "bottom",
    prepare: { tab: "board", clearSelection: true },
  },
  {
    id: "projetos-view",
    target: '[data-tour="projetos-view"]',
    title: "Todos os projetos",
    body: "Clique em um projeto para abrir escopo, demandas, financeiro, credenciais e arquivos.",
    placement: "bottom",
    tooltipDock: "bottom",
    prepare: { tab: "projetos", clearSelection: true, scrollBlock: "start" },
  },
  {
    id: "tab-clientes",
    target: '[data-tour="tab-clientes"]',
    title: "Clientes",
    body: "Cadastro e status de cada cliente. Atalho: ⌘5.",
    placement: "bottom",
    prepare: { tab: "projetos", clearSelection: true },
  },
  {
    id: "clientes-view",
    target: '[data-tour="clientes-view"]',
    title: "Todos os clientes",
    body: "Tabela com contato, importância e status. Clique para abrir o perfil completo do cliente.",
    placement: "bottom",
    tooltipDock: "bottom",
    prepare: { tab: "clientes", clearSelection: true, scrollBlock: "start" },
  },
  {
    id: "tab-lucro",
    target: '[data-tour="tab-lucro"]',
    title: "Lucro",
    body: "Painel financeiro do workspace. Atalho: ⌘6.",
    placement: "bottom",
    prepare: { tab: "clientes", clearSelection: true },
  },
  {
    id: "lucro-view",
    target: '[data-tour="lucro-view"]',
    title: "Painel financeiro",
    body: "Filtros por cliente e projeto, resumo recebido vs orçamento, Top ranking, panorama mensal e tabela de lançamentos.",
    placement: "bottom",
    tooltipDock: "bottom",
    prepare: { tab: "lucro", clearSelection: true, scrollBlock: "start" },
  },
  {
    id: "new-actions",
    target: '[data-tour="new-actions"]',
    title: "Criar no workspace",
    body: "Novo Cliente, Novo Projeto e Nova Demanda — inclusive projetos de 99Freelas, Workana ou próprios.",
    placement: "bottom",
    prepare: { tab: "central", clearSelection: true },
  },
  {
    id: "header-search",
    target: '[data-tour="header-search"]',
    title: "Busca rápida",
    body: "Encontre clientes e projetos na hora. Atalho: ⌘K ou Ctrl+K.",
    placement: "bottom",
    prepare: { tab: "central", clearSelection: true },
  },
  {
    id: "header-settings",
    target: '[data-tour="header-settings"]',
    title: "Configurações",
    body: "Conta, atalhos personalizados, privacidade e MyWallet (integração financeira em breve). Atalho: ⌘,",
    placement: "bottom",
    prepare: { tab: "central", clearSelection: true },
  },
  {
    id: "settings-view",
    target: '[data-tour="settings-view"]',
    title: "Sua conta e preferências",
    body: "Edite perfil e foto, veja atalhos do teclado, políticas de privacidade e o futuro MyWallet para conectar seu controle financeiro.",
    placement: "right",
    prepare: { tab: "configuracoes", clearSelection: true, scrollBlock: "start" },
  },
  {
    id: "settings-nav",
    target: '[data-tour="settings-nav"]',
    title: "Seções de configuração",
    body: "Navegue entre Conta, MyWallet, Atalhos e Privacidade pelo menu lateral.",
    placement: "right",
    prepare: { tab: "configuracoes", clearSelection: true },
  },
  {
    id: "theme-toggle",
    target: '[data-tour="theme-toggle"]',
    title: "Tema claro ou escuro",
    body: "Alterne o tema quando quiser. O MyBoard lembra sua preferência neste navegador.",
    placement: "bottom",
    interactive: true,
    prepare: { tab: "central", clearSelection: true },
  },
  {
    id: "sidebar-right",
    target: '[data-tour="sidebar-right"]',
    title: "Painel direito",
    body: "Notificações, atividades recentes e clientes com acesso rápido ao perfil.",
    placement: "left",
    prepare: { tab: "central", clearSelection: true, rightOpen: true },
  },
  {
    id: "finish",
    title: "Tudo pronto!",
    body: "Você conheceu o MyBoard completo. Crie um cliente, agende um evento na Agenda e registre o primeiro lançamento em Lucro.",
    placement: "center",
    prepare: { tab: "central", clearSelection: true, leftOpen: true, rightOpen: true },
  },
];

export function isOnboardingActive(status) {
  return status === "pending" || status === "in_progress";
}

export function isOnboardingFinished(status) {
  return status === "completed" || status === "skipped";
}
